// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgB5TsTs1_GIo2f-TcZyjTgVDNZfuXN5I',
    appId: '1:1063094620957:web:100eafe3739c2fbe36c7f4',
    messagingSenderId: '1063094620957',
    projectId: 'bingo3000',
    authDomain: 'bingo3000.firebaseapp.com',
    storageBucket: 'bingo3000.appspot.com',
    measurementId: 'G-0CJ7ZM14X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgNym34Aw6lSQWhx38KtEVNyEaSRw1cPM',
    appId: '1:1063094620957:android:aa38309b32928ab336c7f4',
    messagingSenderId: '1063094620957',
    projectId: 'bingo3000',
    storageBucket: 'bingo3000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDauNCgsqogRVV4DXKen1O0noeZ1tAs7yU',
    appId: '1:1063094620957:ios:8cdb9a4d053129bb36c7f4',
    messagingSenderId: '1063094620957',
    projectId: 'bingo3000',
    storageBucket: 'bingo3000.appspot.com',
    iosClientId: '1063094620957-mfu3n4rfunquhka7msov4e3r72fngbv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.host',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDauNCgsqogRVV4DXKen1O0noeZ1tAs7yU',
    appId: '1:1063094620957:ios:8cdb9a4d053129bb36c7f4',
    messagingSenderId: '1063094620957',
    projectId: 'bingo3000',
    storageBucket: 'bingo3000.appspot.com',
    iosClientId: '1063094620957-mfu3n4rfunquhka7msov4e3r72fngbv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.host',
  );
}
