// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLuP5dLYRwpu0AtcQldkCxxO94laW1Hqo',
    appId: '1:845831780402:web:ab249e609a6b2684d7642b',
    messagingSenderId: '845831780402',
    projectId: 'flutter-vikings-bingo',
    authDomain: 'flutter-vikings-bingo.firebaseapp.com',
    storageBucket: 'flutter-vikings-bingo.appspot.com',
    measurementId: 'G-7TKSC49TTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNiDIpPmweGMYa8TgXpdvXZtTfdLo2g1g',
    appId: '1:845831780402:android:4fc171f964736f0ad7642b',
    messagingSenderId: '845831780402',
    projectId: 'flutter-vikings-bingo',
    storageBucket: 'flutter-vikings-bingo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCWD9EZNNk7IwHHr2UzdxbR3t__hp-eMU',
    appId: '1:845831780402:ios:da71434b2ebf435ed7642b',
    messagingSenderId: '845831780402',
    projectId: 'flutter-vikings-bingo',
    storageBucket: 'flutter-vikings-bingo.appspot.com',
    iosClientId: '845831780402-for8fg8p40pd4760v355r3nusv6eku7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.vikingsBingo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCWD9EZNNk7IwHHr2UzdxbR3t__hp-eMU',
    appId: '1:845831780402:ios:da71434b2ebf435ed7642b',
    messagingSenderId: '845831780402',
    projectId: 'flutter-vikings-bingo',
    storageBucket: 'flutter-vikings-bingo.appspot.com',
    iosClientId: '845831780402-for8fg8p40pd4760v355r3nusv6eku7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.vikingsBingo',
  );
}
