// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgB5TsTs1_GIo2f-TcZyjTgVDNZfuXN5I',
    appId: '1:1063094620957:web:100eafe3739c2fbe36c7f4',
    messagingSenderId: '1063094620957',
    projectId: 'bingo3000',
    authDomain: 'bingo3000.firebaseapp.com',
    storageBucket: 'bingo3000.appspot.com',
    measurementId: 'G-0CJ7ZM14X6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgNym34Aw6lSQWhx38KtEVNyEaSRw1cPM',
    appId: '1:1063094620957:android:d9ef28f5bc049a0136c7f4',
    messagingSenderId: '1063094620957',
    projectId: 'bingo3000',
    storageBucket: 'bingo3000.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDauNCgsqogRVV4DXKen1O0noeZ1tAs7yU',
    appId: '1:1063094620957:ios:1cba02952ee3126f36c7f4',
    messagingSenderId: '1063094620957',
    projectId: 'bingo3000',
    storageBucket: 'bingo3000.appspot.com',
    iosClientId: '1063094620957-lqu8e04e5dr20f16cn8vk41sla045453.apps.googleusercontent.com',
    iosBundleId: 'com.example.vikingsBingo',
  );
}
